version: '3'
services:
    ui:
        build: ./ui
        ports:
            - '3000:3000'
        depends_on:
            - api
        stdin_open: true
    api:
        build: ./api
        ports:
            - '8080:8080'
        depends_on: 
            - mongo
            - postgres
    mongo:
        image: mongo
        logging:
            driver: none
        ports:
            - '27017:27017'
    postgres:
        container_name: postgres
        image: postgres
        logging:
            driver: none
        ports:
            - '5432:5432'
        env_file:
            - testing.env
        volumes:
            - ./postgres-data:/var/lib/postgresql/